services:
  - type: web
    name: nextjs-app
    runtime: node
    repo: https://github.com/theerachai1234/Web-Machine.git
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
